Numpy Basics

This notebook explores basics of numpy i.e. arrays, vectors, matrices etc. This is the first step towards learning scientif 
computing with python, since every algorithm requires dealing with data in some form or another.

In this notebook we will try to clear some fundamentals which are invariably required later in AI/NN based algorithms. 
Most important will be data representation (array, vectors, matrices), data manipulation (conversion between arary to vector) and operations (append, stack, slice etc).

In [43]:
import numpy as np
np.random.seed(0)

In [44]:
#Simple 1D-array object.
normalArr = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])
normalArr

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [45]:
#Creating a 1D-array with range function.
rangeArr = np.arange(0, 10, 1)
rangeArr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
#Creating a 1D-array with linspace function.
linspaceArr = np.linspace(0, 20, 5)
linspaceArr

array([ 0.,  5., 10., 15., 20.])

In [47]:
#Checking shape. Since it is a 1-D array the shape will turn out to be (n,).
normalArr.shape

(10,)

In [48]:
#Indexing
normalArr[4:7]

array([50, 60, 70])

In [49]:
#Get every alternate element from 0-9 index.
normalArr[0:9:2]

array([10, 30, 50, 70, 90])

In [50]:
#Get every third element from 0-9 index.
normalArr[0:9:3]

array([10, 40, 70])

In [51]:
#Reverse all elements of normalArr
normalArr[::-1]

array([100,  90,  80,  70,  60,  50,  40,  30,  20,  10])

In [52]:
#2-D array definition.
array2D = np.array([
                        [1,  2, 3, 4],
                        [11,12,13,14],
                        [21,22,23,24],
                        [31,32,33,34]
                  ])

In [53]:
#2D array slicing, all rows 2nd columns
array2D[:,2]

array([ 3, 13, 23, 33])

In [54]:
#2D array slicing, all rows 2 columns
array2D[:,:2]

array([[ 1,  2],
       [11, 12],
       [21, 22],
       [31, 32]])

In [55]:
#2D array slicing, all rows and alternate columns
array2D[:,::2]

array([[ 1,  3],
       [11, 13],
       [21, 23],
       [31, 33]])

In [56]:
#2D array slicing, all rows and alternate columns starting from index 1.
array2D[:,1::2]

array([[ 2,  4],
       [12, 14],
       [22, 24],
       [32, 34]])

In [57]:
#Array, vector, reshaping.
array2vec = np.arange(0,9, 1)
array2vec

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [58]:
array2vec.shape

(9,)

In [68]:
#Convert the array to row vector. In neural netowrks, we need row/column vectors for matrix operations. So, it is always useful
#keep the dimensions in (n*m) form instead of (n,) form.
array2vec = array2vec.reshape((1,9))
array2vec

array([[0, 1, 2, 3, 4, 5, 6, 7, 8]])

In [69]:
array2vec.shape

(1, 9)

In [70]:
#Convert array2vec into column vector.
array2vec = array2vec.reshape((9,1))
array2vec

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [71]:
array2vec.shape

(9, 1)

Stacking- It is used to combine arrays. Either row wise or column-wise.

In [73]:
array2r3c = np.arange(0, 6, 1).reshape(2,3)
array2r3c

array([[0, 1, 2],
       [3, 4, 5]])

In [74]:
array1r3c = np.arange(0,3,1)
array1r3c

array([0, 1, 2])

In [76]:
#Stack the above defined array's vertically.
arrayvstack = np.vstack([array2r3c, array1r3c])
arrayvstack

array([[0, 1, 2],
       [3, 4, 5],
       [0, 1, 2]])

In [77]:
array2r1c = np.arange(0,2,1).reshape(2,1)
array2r1c

array([[0],
       [1]])

In [78]:
#Stack the above defined array's horizontally.
arrayhstack = np.hstack([array2r3c, array2r1c])
arrayhstack

array([[0, 1, 2, 0],
       [3, 4, 5, 1]])

In [88]:
#Append one array to another one.
array1D = np.arange(11,14,1)
array1D

array([11, 12, 13])

In [89]:
appendedArray = np.append(arrayvstack, array1D.reshape(1,3), axis=0)
appendedArray

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 0,  1,  2],
       [11, 12, 13]])

In [90]:
appendedArray = np.append(arrayvstack, array1D.reshape(3,1), axis=1)
appendedArray

array([[ 0,  1,  2, 11],
       [ 3,  4,  5, 12],
       [ 0,  1,  2, 13]])

Random: Random numbers are used at several places. Typically when assigning a variable (such as weight initialization in neural
networks). 

In [91]:
#Uniform distribution from 0 to 1.
randomArray = np.random.rand(3,3)
randomArray

array([[0.5488135 , 0.71518937, 0.60276338],
       [0.54488318, 0.4236548 , 0.64589411],
       [0.43758721, 0.891773  , 0.96366276]])

In [92]:
#Random matrix from standard normal distribution.
randomArrayRand = np.random.randn(3,3)
randomArrayRand

array([[ 1.26611853, -0.50587654,  2.54520078],
       [ 1.08081191,  0.48431215,  0.57914048],
       [-0.18158257,  1.41020463, -0.37447169]])

In [94]:
#Random numbers between 0 and 10 with shape (3,3)
randomArrayRandint = np.random.randint(10, size=(3,3))
randomArrayRandint

array([[0, 1, 9],
       [9, 0, 4],
       [7, 3, 2]])

In [97]:
#Min, Max, sum.
randomArrayRandint.max(axis=0)

array([9, 3, 9])

In [96]:
randomArrayRandint.max(axis=1)

array([9, 9, 7])

In [98]:
randomArrayRandint.sum()

35